name: Build and Push Docker Image

on:
  push:
    branches:
      - Development  # Change this to your deployment branch if necessary

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ap-south-1
      # Now using a secret for the ECR repository URI
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to AWS ECR. This action automatically uses AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY if set as secrets.
      - name: Login to AWS ECR
        id: ecr_login
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: ${{ env.AWS_REGION }}

      # Build the Docker image
      - name: Build Docker Image
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .

      # Push the Docker image to ECR
      - name: Push Docker Image to ECR
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}
          docker push $ECR_REPOSITORY:$IMAGE_TAG
